#!/bin/zsh

git init
touch .gitignore
echo "*.env" >> .gitignore

git stage -A
git commit -m "init commit"

if [[ $1 != "-l" || $1 != "--local" ]]; then
    gh repo create 
    git push --set-upstream origin main
fi
