#!/bin/zsh

# This is the intial install script for quaxlyqueen/scripts.
# It will install the scripts and set up the environment.

# Install the scripts
echo "Installing scripts..."
sudo cp * /usr/local/bin

# Set up the environment
echo "Setting up the environment..."
echo "export PATH=$PATH:/usr/local/bin" >> ~/.zshrc

# Install the dependencies
echo "Installing dependencies..."
# Install github-cli
