#!/bin/zsh

TARGET_FILE=~/.config/xob/brightness
PIPE=~/.config/xob/xobpipe
OLDNUM=`cut -f1 $TARGET_FILE`

tail -f $PIPE | xob -s brightness &
if [[ $# -eq 0 ]]; then
  NEWNUM=`expr $OLDNUM + 5`
elif [[ $# -eq 1 ]]; then
  NEWNUM=$1
elif [[ $# -eq 2 ]]; then
  if [[ $1 -eq "--decrease" ]]; then
    CHANGE=`expr 0 - $2`
  elif [[ $1 -eq "--increase" ]]; then
    CHANGE=$2
  fi
  NEWNUM=`expr $OLDNUM + $CHANGE`
fi

if [[ $NEWNUM -le 100 && $NEWNUM -ge 0 ]]; then
  sed -i "s/$OLDNUM/$NEWNUM/g" $TARGET_FILE
  brightnessctl set $NEWNUM%
  echo $NEWNUM >> $PIPE
fi
